name: Documentation

on:
  push:
    branches:
      - master
      - 'release-'
    tags: '*'
  pull_request:

jobs:
  build:
    permissions:
      actions: write
      contents: write
      pull-requests: read
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: "Start SSH agent"
        uses: "webfactory/ssh-agent@d4b9b8ff72958532804b70bbe600ad43b36d5f2e" # v0.8.0
        with:
          ssh-private-key: "${{ secrets.DOCUMENTER_KEY }}"
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(url="git@github.com:Neuroblox/Neuroblox.jl.git")); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY_DEPLOY }} # For authentication with SSH deploy key
        run: julia --project=docs/ --code-coverage=user docs/make.jl
      - uses: julia-actions/julia-processcoverage@v1
        with:
          directories: src
      - uses: codecov/codecov-action@v4
        with:
          files: lcov.info
